### ISSUE TITLE
Czas najwyższy przejść na Django 1.7

### ISSUE THREAD

**Issue by geodotka** [geodotka/dimgem#49]

**Comment by Cosiek** [comment]
Biorąc pod uwagę nasze dzisiejsze doświadczenia - wstrzymałbym się jeszcze kilka dni.

**Comment by nder** [comment]
:speak_no_evil: :+1:

**Comment by geodotka** [comment]
Bardzo mi się podobają Wasze komentarze. Myślę, że za flagą nic się u mnie nie ukrywa :alien:
