### ISSUE TITLE
Wyszukiwanie - tylko całe wyrazy

### ISSUE THREAD

**Issue by geodotka** [geodotka/dimgem#55]
Na prośbę GEM rozszerzyć wyszukwianie o checkboxa, po zaznaczeniu będzie wyszukiwał tylko całe wyrazy.

**Comment by Cosiek** [comment]
Podpowiedź:
```python
import re

txt = (u"Ala ma kota, "
    u"a kot ALA to idiota, "
    u"bo ala lubi głupie koty. "
    u"Zwłaszcza jak miałczą bambala. "
    u"Co poradzisz - poprostu aLa")

search_word = u'ala'
#search_word = u'głupie'
#search_word = u'kot'

# re.I - case insensitive, re.U - obsługa unicode
pattern = re.compile(r'\b(' + search_word + r')\b', flags=(re.I | re.U))
repl = r'<strong>\1</strong>'

print re.sub(pattern, repl, txt)
```

Tylko pobieżnie przetestowane, ale powinno działać.

**Comment by geodotka** [comment]
@Cosiek, wielkie dzięki, za niedługo to przetestuję jeszcze w tamtym zadaniu, niby już wciągnięte, ale zawsze można zrobić puszforsa na mastera ;)
Czekamy na następne nitki :tram:  na ścianie
